name: .NET

on:
  push:
    branches:
    - "main"
    tags-ignore:
    - "v*"

jobs:
  build:
    runs-on: windows-latest

    env:
      config: Release
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration $config

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Zip Release Folder
      run: Compress-Archive -Path .\Phloem\bin\Release\netcoreapp3.1\ -DestinationPath .\phloem.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        name: Development Build
        tag_name: latest
        prerelease: true
        files: |
          phloem.zip
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
